export { Home as PageHome} from "./Home"
export { Layout as PageLayout } from "./Layout"
export { Receitas as PageReceitas} from "./Receitas"
export { Adicionar as PageAdicionar } from "./Adicionando"
export { Pix as PagePix } from "./Pix"